#!/usr/bin/env python

import argparse
import os
import sys

from mako.template import Template

parser = argparse.ArgumentParser(
    description="Renders template with environment variables.",
)
parser.add_argument("template", type=argparse.FileType("r"), default=sys.stdin)
parser.add_argument("-o", "--out", type=argparse.FileType("w"), default=sys.stdout)

args = parser.parse_args()

template = Template(args.template.read())

args.out.write(template.render(**os.environ))
args.out.close()

# vim:ft=python
